export interface ThumbnailObject {
  quality: string;
  url: string;
  width: number;
  height: number;
}

export interface ImageObject {
  url: string;
  width: number;
  height: number;
}

export interface VideoObject {
  type: 'video';
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified?: boolean;
  videoThumbnails: ThumbnailObject[];
  description?: string;
  descriptionHtml?: string;
  viewCount?: number;
  viewCountText?: string;
  lengthSeconds?: number;
  published?: number;
  publishedText?: string;
  premiereTimestamp?: number;
  liveNow?: boolean;
  premium?: boolean;
  isUpcoming?: boolean;
  isNew?: boolean;
  is4k?: boolean;
  is8k?: boolean;
  hasCaptions?: boolean;
}

export interface ChannelObject {
  type: 'channel';
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified?: boolean;
  authorThumbnails: ThumbnailObject[];
  autoGenerated?: boolean;
  subCount?: number;
  videoCount?: number;
  description?: string;
  descriptionHtml?: string;
}

export interface PlaylistObject {
  type: 'playlist';
  title: string;
  playlistId: string;
  playlistThumbnail?: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified?: boolean;
  videoCount?: number;
  videos: {
    title: string;
    videoId: string;
    lengthSeconds: number;
    videoThumbnails: ThumbnailObject[];
  }[];
}

export interface SearchResult {
  type: 'video' | 'playlist' | 'channel' | 'hashtag';
  [key: string]: unknown;
}

export interface VideoDetails {
  type: string;
  title: string;
  videoId: string;
  videoThumbnails: ThumbnailObject[];
  storyboards?: { url: string; templateUrl: string; width: number; height: number; count: number; interval: number; }[];
  description: string;
  descriptionHtml: string;
  published: number;
  publishedText: string;
  keywords: string[];
  viewCount: number;
  likeCount: number;
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: ThumbnailObject[];
  subCountText: string;
  lengthSeconds: number;
  allowRatings: boolean;
  rating: number;
  isListed: boolean;
  liveNow: boolean;
  isUpcoming: boolean;
  premiereTimestamp?: number;
  hlsUrl?: string;
  dashUrl?: string;
  formatStreams: FormatStream[];
  adaptiveFormats: AdaptiveFormat[];
  captions: Caption[];
  recommendedVideos: RecommendedVideo[];
}

export interface FormatStream {
  url: string;
  mimeType: string;
  container: string;
  encoding: string;
  quality: string;
  qualityLabel: string;
  resolution: string;
  fps: number;
  bitrate: string;
  clen?: string;
}

export interface AdaptiveFormat {
  index: string;
  bitrate: string;
  init: string;
  url: string;
  mimeType: string;
  container: string;
  encoding: string;
  qualityLabel: string;
  resolution: string;
  fps?: number;
  audioQuality?: string;
  audioSampleRate?: number;
  audioChannels?: number;
}

export interface Caption {
  label: string;
  languageCode: string;
  url: string;
}

export interface RecommendedVideo {
  videoId: string;
  title: string;
  author: string;
  authorId: string;
  authorThumbnails: ThumbnailObject[];
  videoThumbnails: ThumbnailObject[];
  viewCount: number;
  lengthSeconds: number;
}

export interface Comment {
  author: string;
  authorThumbnails: ThumbnailObject[];
  authorId: string;
  authorUrl: string;
  isEdited: boolean;
  isPinned: boolean;
  isSponsor?: boolean;
  content: string;
  contentHtml: string;
  published: number;
  publishedText: string;
  likeCount: number;
  commentId: string;
  authorIsChannelOwner: boolean;
  replyCount?: number;
  replies?: Comment[];
}

export interface CommentsResponse {
  commentCount: number;
  videoId: string;
  comments: Comment[];
  continuation?: string;
}

export interface ChannelDetails {
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  authorBanners: ImageObject[];
  authorThumbnails: ThumbnailObject[];
  subCount: number;
  totalViews: number;
  joined: number;
  autoGenerated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  allowedRegions: string[];
  tabs: string[];
  pronouns?: string;
  latestVideos: VideoObject[];
  relatedChannels: ChannelObject[];
}

export interface ChannelVideosResponse {
  videos: VideoObject[];
  continuation?: string;
}

export interface ChannelPlaylistsResponse {
  playlists: PlaylistObject[];
  continuation?: string;
}

export interface PlaylistDetails {
  title: string;
  playlistId: string;
  playlistThumbnail?: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified?: boolean;
  description?: string;
  videoCount: number;
  videos: {
    title: string;
    videoId: string;
    lengthSeconds: number;
    videoThumbnails: ThumbnailObject[];
    author?: string;
    authorId?: string;
  }[];
}

export interface MixResponse {
  mixId: string;
  playlistId: string;
  title: string;
  videos: VideoObject[];
  continuation?: string;
}

export interface SearchFilters {
  sort_by?: 'relevance' | 'rating' | 'upload_date' | 'view_count';
  date?: 'hour' | 'today' | 'week' | 'month' | 'year';
  duration?: 'short' | 'long';
  type?: 'video' | 'playlist' | 'channel' | 'all';
  features?: string[];
  region?: string;
}

export interface CommunityPost {
  attachment?: unknown;
  author: string;
  authorIsChannelOwner: boolean;
  authorId: string;
  authorThumbnails: ImageObject[];
  authorUrl: string;
  commentId: string;
  content: string;
  contentHtml: string;
  isEdited: boolean;
  likeCount: number;
  published: number;
  publishedText: string;
  replyCount: number;
}
